# Read the Docs configuration file for pytestee
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install uv for faster dependency management
      - pip install uv
    post_install:
      # Install project dependencies and docs dependencies
      - uv sync --group docs

mkdocs:
  configuration: mkdocs.yml

formats:
  - pdf
  - epub

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs