name: Publish Python Package

on:
  release:
    types: [published]

permissions:
  contents: read
  actions: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Download release assets
        run: |
          gh release download ${{ github.ref_name }} --pattern "*.whl" --pattern "*.tar.gz" --dir dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  actions-timeline:
    needs: release
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: Kesin11/actions-timeline@7c7e0821d38f27460f4a71ef874a1c8cf23602e4 # v2.2.6
